language: node_js
version: 1.0
node_js:
- '12.13'
cache:
  directories:
    - node_modules
before_deploy: "node run.js"
deploy:
  edge: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    branch: production
